### ISSUE TITLE
Dynamic records without monitoring

### ISSUE THREAD

**Issue by jimaek** [octodns/octodns-ns1#28]
I simply want to create some dynamic records to do geo routing. e.g. requests from Germany should get de.example.com and everyone else all.example.com

But the system currently tries to create a monitoring job for every single dynamic record even though its not needed https://dl.dropboxusercontent.com/s/w58l37825k2dnom/chrome_2022-12-14_19-34-33.png

Basically it should work with all these permissions disabled https://dl.dropboxusercontent.com/s/bp5x52o88upgbu2/chrome_2022-12-14_19-43-09.png

It it possible to decouple this functionality?

**Comment by viranch** [comment]
Yes you can set `status: up` for each pool value that you don't want to monitor. See https://github.com/octodns/octodns/blob/main/docs/dynamic_records.md#health-checks

**Comment by ross** [comment]
See the [Health Checks](https://github.com/octodns/octodns/blob/main/docs/dynamic_records.md#health-checks) section of the `dynamic` records documentation. According to the doc NS1 supports all 3 values so that should include `up` which means just assume the endpoints are healthy. It's been a while since I was in that code so I'm not sure what exactly `Ns1Provider` does to implement it, there may still be a health check set up, but either way it'll always assume it's healthy.

**Comment by viranch** [comment]
It skips the monitor creation for status:up answers.

**Comment by jimaek** [comment]
In that case shouldn't this be working? I dont see what I am doing wrong

```
'dynamic-geo':
  # This is a dynamic record when used with providers that support it
  dynamic:
    # These are the pools of records that can be referenced and thus used by rules
    pools:
      apac:
        # One or more values for this pool
        values:
        - value: apac1.example.com.
          status: up
        - value: apac2.example.com.
          status: up
      eu:
        values:
        - value: eu1.example.com.
          # Weight for this value, if omitted the default is 1
          weight: 2
          status: up
        - value: eu2.example.com.
          weight: 3
          status: up
      na:
        # Implicit fallback to the default pool (below)
        values:
        - value: northamerica.example.com.
          status: up
    # Rules that assign queries to pools
    rules:
    - geos:
      # Geos used in matching queries
      - AS
      - OC
      # The pool to service the query from
      pool: apac
    - geos:
      - AF
      - EU
      pool: eu
    # No geos means match all queries
    - pool: na
  ttl: 60
  type: CNAME
  value: last.example.com.
```

error
```
yaml.constructor.ConstructorError: keys out of order: expected status got value at   in "./config/testzone.io.yaml", line 16, column 11
```

16 is this line `        - value: apac1.example.com.`
