### ISSUE TITLE
Synthetic ocean region has incorrect priority.

### ISSUE THREAD

**Issue by istr** [octodns/octodns-ns1#36]
The ns1 provider does not have a separate "Continental Australia/Oceania" global region.

This region is mimicked using a country-based region. In combination with an apac region, this will never be used, because the priority is not set in the correct order.

Observed behavior:
Requests from Australia are served from the APAC entry, not from the OCEAN entry.

Expected behavior:
Requests from Australia are served from the OCEAN entry.

Proposed fix: always put the priority of geo regions in "most specific" to "least specific" order.

ns1 provides the following geo regions:
```
US-EAST
US-CENTRAL
US-WEST
EUROPE
ASIAPAC
SOUTH-AMERICA
AFRICA
```

The `ocean` region will be created as a country region.
```
ANSWER GROUP: OCEAN__COUNTRY
country: WF, WS, FJ, FM, PW, TV, NC, NF, TO, NZ, PF, TK, NR, PN, NU, PG, CK, GU, AS, AU, VU, KI, MH, MP, SB
note: continents:OC rule-order:9
```

With the following record, all requests from `ocean` will be routed to `apac`, because the `apac` rule is created with a higher priority.

```
cdn-dev:
  - dynamic:
      pools:
        af:
          values:
            - status: up
              value: 68.70.192.128
        apac:
          values:
            - status: up
              value: 89.187.160.25
            - status: up
              value: 89.187.160.31
        eu:
          values:
            - status: up
              value: 185.172.148.128
            - status: up
              value: 185.172.148.132
        eu_E:
          values:
            - status: up
              value: 137.74.0.47
            - status: up
              value: 146.59.70.106
        eu_SW:
          values:
            - status: up
              value: 82.102.17.19
        eu_fr:
          values:
            - status: up
              value: 62.210.90.237
            - status: up
              value: 62.210.90.238
        eu_nl:
          values:
            - status: up
              value: 185.172.149.128
            - status: up
              value: 185.172.149.132
        eu_uk:  # also used for af
          values:
            - status: up
              value: 68.70.192.128
        na:
          values:
            - status: up
              value: 138.199.57.66
            - status: up
              value: 138.199.57.67
        ocean:
          values:
            - status: up
              value: 103.231.91.78
        sa:
          values:
            - status: up
              value: 87.249.130.6
      rules:
        # 'AF': 14, # Continental Africa
        # 'AN': 17, # Continental Antarctica
        # 'AS': 15, # Continental Asia
        # 'EU': 13, # Continental Europe
        # 'NA': 11, # Continental North America
        # 'OC': 16, # Continental Australia/Oceania
        # 'SA': 12, # Continental South America
        - geos:
            - AF
          pool: af  # from UK, probably using 2Africa submarine cable
        - geos:
            - AS
          pool: apac
        - pool: eu
        - geos:
            - EU-UA
            - EU-PL
            - EU-RU
            - EU-LT
            - EU-LV
            - EU-EE
          pool: eu_E
        - geos:
            - EU-AD
            - EU-ES
            - EU-PT
          pool: eu_SW
        - geos:
          - EU-FR
          - EU-MC
          pool: eu_fr
        - geos:
          - EU-NL
          pool: eu_nl
        - geos:
            - EU-GB
          pool: eu_uk
        - geos:
            - NA
          pool: na
        - geos:
            - OC
          pool: ocean
        - geos:
            - SA
          pool: sa
    ttl: 60
    type: A
    values:
      - 185.172.148.128
      - 185.172.148.132
 ```

**Comment by ross** [comment]
Looking more closely at the example above I realized the `pool: eu` rule has no geos:

```yaml
        - geos:
            - AS
          pool: apac
        - pool: eu
        - geos:
            - EU-UA
            - EU-PL
            - EU-RU
            - EU-LT
            - EU-LV
            - EU-EE
          pool: eu_E
```

That would make it a matches everything rule. Not yet sure if that's THE problem here, but it's definitely going to lead to unexpected/unintended behaviors. I'm guessing there's a missing `geos: [EU]` there?

Otherwise since rules are intended to be applied in order the best practice would be to have them in order from most to least specific to the degree possible, i.e. `continent-country-state`, `continent-country`, `continent`, and finally the catchall. (doesn't appear to be a catchall in the above config)

My reworked rules are:

```yaml
      rules:
        # 'AF': 14, # Continental Africa
        # 'AN': 17, # Continental Antarctica
        # 'AS': 15, # Continental Asia
        # 'EU': 13, # Continental Europe
        # 'NA': 11, # Continental North America
        # 'OC': 16, # Continental Australia/Oceania
        # 'SA': 12, # Continental South America
        - geos:
            - EU-UA
            - EU-PL
            - EU-RU
            - EU-LT
            - EU-LV
            - EU-EE
          pool: eu_E
        - geos:
            - EU-AD
            - EU-ES
            - EU-PT
          pool: eu_SW
        - geos:
            - EU-FR
            - EU-MC
          pool: eu_fr
        - geos:
            - EU-NL
          pool: eu_nl
        - geos:
            - EU-GB
          pool: eu_uk
        - geos:
            - AF
          pool: af  # from UK, probably using 2Africa submarine cable
        - geos:
            - AS
          pool: apac
        - geos: 
            - EU
          pool: eu
        - geos:
            - OC
          pool: ocean
        - geos:
            - SA
          pool: sa
        - pool: na
```

Still looking over the results to see if that gets the "desired" behavior, but https://github.com/octodns/octodns-ns1/issues/35 is complicating things so I may need to figure out what's going on there first.

Running out of time to dig into it today and I'm mostly AFK tomorrow so may be Tuesday before I get a chance to really dig in.

**Comment by ross** [comment]
Started up a global measurement of my reordered config above: https://atlas.ripe.net/measurements/51337336/#general

It's a pain to try and validate things by hand, but it can be done. I might sit down and write up a jupyter-lab notebook to do it as that's what I always did in the past when testing github stuff.

**Comment by istr** [comment]
> Looking more closely at the example above I realized the `pool: eu` rule has no geos:

Yes, this is in fact a catch-all. But this is not a problem -- in APAC vs OCEAN this plays no role, whatsoever.

I just stripped the comments from my config, the original says:
```
- pool: eu  # catchall for NS1 - no geos
```

**Comment by istr** [comment]
> Running out of time to dig into it today and I'm mostly AFK tomorrow so may be Tuesday before I get a chance to really dig in.

Yes, I will try to check what's going on in #35 as well...

**Comment by istr** [comment]
Let me elaborate on the _catchall_ approach.

```yaml
cdn-dev:
  - dynamic:
      pools:
...
        eu:
          values:
            - status: up
              value: 185.172.148.128
            - status: up
              value: 185.172.148.132
...
      rules:
...
        - pool: eu  # catchall for NS1 - no geos
```

is the catchall rule specifically for the ns1 provider, because it does not support the global fallback set in `values`, that is used for all other providers (and is identical):

```yaml
    ttl: 60
    type: A
    values:
      - 185.172.148.128
      - 185.172.148.132
```

I think that I had mentioned this quirk elsewhere in some related discussion already... :slightly_smiling_face:
