### ISSUE TITLE
Geo rule for Asia pulls in Oceania also

### ISSUE THREAD

**Issue by viranch** [octodns/octodns-ns1#38]
Something that crossed my mind while testing #37: the mapping of `AS` continent to NS1's `ASIAPAC` region inadvertently pulls in all non-Asian (ie, Oceania) countries also to that rule. Example:

```
www:
  ttl: 300
  type: CNAME
  value: def.odns.io.
  dynamic:
    pools:
      as:
        values:
        - value: as.odns.io.
          status: up
      world:
        values:
        - value: any.odns.io.
          status: up
    rules:
    - geos: [AS]
      pool: as
    - pool: world
```

The above record should hand out the `world` pool for clients from Oceania. But due to the above mapping, NS1 will hand out `as` pool for them, which can be against user's expectations since octodns offers another `OC` continent separate from `AS`.

One solution can be to duplicate the catch-all rule and put Oceania in there. If one doesn't exist, point `OC` to the top-level default.
